### ISSUE TITLE
Example Code Incorrect for business_match_query

### ISSUE THREAD

**Issue by AlanZZhao** [gfairchild/yelpapi#10]
If you use the current examples of 
print('***** search for business best match *****\n{}\n'.format("yelp_api.business_match_query(name='Splash Cafe', "
                                                                "city='Pismo Beach', state='CA', country='US')"))
response = yelp_api.business_match_query(name='Splash Cafe', city='Pismo Beach', state='CA', country='US')
pprint(response)

from the example.py file: https://github.com/gfairchild/yelpapi/blob/master/examples/examples.py

You get nothing, an empty dict.

API now requires an address for the business lookup:
https://github.com/Yelp/yelp-fusion/issues/412

Should just be a quick fix to include the address for splash cafe:
197 Pomeroy Ave
Pismo Beach, CA 93449

So that the examples work.

**Comment by gfairchild** [comment]
Thanks for the report. I’ll take care of this this week/weekend.

**Comment by gfairchild** [comment]
Closed by #12
