### ISSUE TITLE
YelpAPI(api_key) error:  __init__() takes exactly 5 arguments (2 given)

### ISSUE THREAD

**Issue by iwannabetall** [gfairchild/yelpapi#13]
I tried something like the first examples for searching for businesses and got this error:  __init__() takes exactly 5 arguments (2 given) 

```
from yelpapi import YelpAPI
yelp_api = YelpAPI(api_key)
search_results = yelp_api.search_query(args)
```

So then I tried to get the first part from https://github.com/gfairchild/yelpapi/blob/master/examples/examples.py, 
```
from yelpapi import YelpAPI
import argparse
from pprint import pprint

argparser = argparse.ArgumentParser(description='Example Yelp queries using yelpapi. '
                                                'Visit https://www.yelp.com/developers/v3/manage_app to get the '
                                                'necessary API keys.')
argparser.add_argument('api_key', type=str, help='Yelp Fusion API Key')
args = argparser.parse_args()

yelp_api = YelpAPI(args.api_key)
```

and I get this error when I get to this line
args = argparser.parse_args()
usage: [-h] api_key
: error: too few arguments

What am I doing wrong? I dont know what other args to add...

**Comment by gfairchild** [comment]
Are you actually passing your API key as an argument? Can you show me how you're calling your code?

**Comment by iwannabetall** [comment]
I tried downloading the examples file and calling it in my terminal like this at the top of the file
"""
    Example call:
        ./examples.py "[API Key]"
"""

ran this in my terminal:
`python examples.py "MY API KEY"` and got this
```
[Traceback (most recent call last):

  File "yelpAPIexamples.py", line 39, in <module>
    yelp_api = YelpAPI(args.api_key)
TypeError: __init__() takes exactly 5 arguments (2 given)](url)
```

I also tried running this in python in my terminal line by line (where api_key = 'whatever my API KEY is')
```
from yelpapi import YelpAPI
yelp_api = YelpAPI(api_key)  
search_results = yelp_api.search_query(args)

```
and just the YelpAPI(api_key) gives me an error:
```
>>> YelpAPI(API_KEY)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: __init__() takes exactly 5 arguments (2 given)
```

**Comment by gfairchild** [comment]
I'm not able to replicate this error on my environment. Can you tell me what version of `yelpapi` you're using? What version of Python are you using?

**Comment by iwannabetall** [comment]
I think it's v1.4 for yelpapi?  (I just installed it)...and python 2.7.

How are you calling the file/function?  exactly the same way?

**Comment by gfairchild** [comment]
@iwannabetall, are you still seeing this error? Did you try the suggestions I had in my last post?

**Comment by gfairchild** [comment]
I'm going to go ahead and close this issue given the lack of response. If you're still experiencing this issue, please feel free to reopen.
