### ISSUE TITLE
can we get business emails from yelp fusion api

### ISSUE THREAD

**Issue by shyam-infraon** [gfairchild/yelpapi#16]
can we get business emails from yelp fusion API?

**Comment by gfairchild** [comment]
I don't believe so. Looking at the [business details endpoint documentation](https://www.yelp.com/developers/documentation/v3/business), I don't see any email field.

This project isn't the most ideal place for this question. I'd point you to the [official Yelp Fusion API GitHub project](https://github.com/Yelp/yelp-fusion). I might suggest you follow up there with any questions specifically about how the API operates.
