### ISSUE TITLE
Missing Token Error after using YelpAPI  for several times

### ISSUE THREAD

**Issue by iceriverg** [gfairchild/yelpapi#4]
I am trying to search some Yelp data this yelpapi, and it works well. However, after running the scripts a coupler of days, it come up always the problem as below. If I use a new app ID, then it works again, but a coupler of days later, same error message came up. Is this caused by Yelp app ID lifetime authorization (but I just use this ID for a coupler of days, and total running Yelp requests less than 10 times ), or we have to find another way to fetch token? the error message is below:

  File "build/bdist.macosx-10.6-intel/egg/yelpapi/yelpapi.py", line 64, in __init__
    self._yelp_session.fetch_token(token_url=ACCESS_TOKEN_URL, client_id=client_id, client_secret=client_secret)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/requests_oauthlib/oauth2_session.py", line 244, in fetch_token
    self._client.parse_request_body_response(r.text, scope=self.scope)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/clients/base.py", line 409, in parse_request_body_response
    self.token = parse_token_response(body, scope=scope)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 376, in parse_token_response
    validate_token_parameters(params)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/oauthlib/oauth2/rfc6749/parameters.py", line 386, in validate_token_parameters
    raise MissingTokenError(description="Missing access token parameter.")
MissingTokenError: (missing_token) Missing access token parameter.

**Comment by gfairchild** [comment]
Can I see some code showing how you're using YelpAPI?

**Comment by gfairchild** [comment]
And to answer your question, yes, I think this is likely a bug related to refreshing the token.

**Comment by gfairchild** [comment]
According to the [Yelp API documentation](https://www.yelp.com/developers/documentation/v3/get_started), the `expires_in` field in the response body is always given a value of 15552000 (180 days). However, after looking at the ]Yelp API issue tracker](https://github.com/Yelp/yelp-fusion), it looks like this may actually not be true (see [this open issue](https://github.com/Yelp/yelp-fusion/issues/98), for example). [This open issue](https://github.com/Yelp/yelp-fusion/issues/84) mentions that subsequent calls to the API will decrement this value, which is what I'm guessing is causing your error to pop up.

**Comment by iceriverg** [comment]
Thanks a lot for quick reply! Here it is my code, exactly copy from your example.
`import json
from yelpapi import YelpAPI
from pprint import pprint

client_id="myid"
client_secret="my_secret"
yelp_api = YelpAPI(client_id, client_secret)

response = yelp_api.search_query(term='',categories='localflavor', longitude=-2.239001, latitude=53.472077, radius=2000, sort_by='best_match', limit=5)
print('\n-------------------------------------------------------------------------\n')
n=response['total']
m=0
print n
for unit in response['businesses']:
    print unit['coordinates']
    print unit['name']
    m+=1
    if m is n:
        break
print "done"   
`

**Comment by iceriverg** [comment]
I was thinking of one potential problem after looking through yelpapi code. It seems every time running the script, it will run the code "YelpAPI(client_id, client_secret)". Does that mean the code will fetch a new access token every time? And then there is a maximum number limit of access tokens which cause this problem?

If that is the case, maybe we have to find a way to not fetch a new access token. Instead we might use the previous access token generated last time, as the access token will expire after 180 days. Then probably we can pass this old access token through YelpAPI(client_id, client_secret, access_token)?

There is no test done yet, so it is total a guess.

**Comment by iceriverg** [comment]
Thanks also point me to open issue #78, #84. It seems in whatever case my access token shouldn't expire just in a couple of days. Return to my last comment, it would be easy to try if I can extract the access token and used in script, but no idea how I can do it.(any suggestion?)

I will also try more times, to see how often this issue happen.

**Comment by gfairchild** [comment]
Thanks for your code. I need to play around with this a bit to diagnose it. I don't think this will be a difficult thing to fix.

**Comment by gfairchild** [comment]
Sorry I haven't had a chance to get to this yet. Work has been pure insanity.

**Comment by gfairchild** [comment]
@iceriverg, are you still experiencing this issue? I ran your example code above, and it's not returning any errors at all.

**Comment by zolrath** [comment]
I just hit this while testing a script that initializes the library when run.

I've been running the script intermittently, probably 20 times in the last hour. The script isn't actually performing any Yelp API requests but during initialization it did make an YelpAPI client.

I ran the script, it succeeded.
About 2 minutes later the script failed.
I ran the script one more time about 10 seconds after the failure and it succeeded.

Same error message as the original report.

**Comment by gfairchild** [comment]
@zolrath, can you provide the script you've been running?

**Comment by gfairchild** [comment]
@zolrath, is just re-running the `examples.py` script a bunch enough to cause this on your end?

**Comment by gfairchild** [comment]
PR #8 (courtesy @tamos) should fix this issue since Yelp will no longer be reliant on OAuth. I'm going to go ahead and close this issue. Please reopen if you continue to experience this issue.
