### ISSUE TITLE
No business match API?

### ISSUE THREAD

**Issue by tlc** [gfairchild/yelpapi#6]
https://www.yelp.com/developers/documentation/v3/business_match

**Comment by gfairchild** [comment]
This is a new endpoint I didn't know existed! Thanks for the heads up.

**Comment by gfairchild** [comment]
FYI, 2 things:

1. I just noticed that @zolrath forked this project and has added a commit introducing this endpoint ([here](https://github.com/zolrath/yelpapi)). If he submits a PR, I'll review it and add it. If not, I can pretty easily add this myself.
1. Note that this endpoint is in beta. If you visit https://www.yelp.com/developers/documentation/v3/business_match without being enrolled in the developer beta program, you'll see this message at the top:

> To enable this endpoint, please join the [Yelp Developer Beta Program](https://www.yelp.com/developers/v3/manage_app).

This isn't a huge deal, but it is something to be aware of. I'm comfortable adding support for a beta endpoint to this project.

**Comment by gfairchild** [comment]
@tlc, know that @zolrath just added support for this new endpoint. I haven't had a chance to push the changes to PyPI yet, though.

**Comment by tlc** [comment]
Just FYI,
I rolled my own and tried their API and it wasn't what I hoped.  There are many Issues for this API, some closed.

This one is the worst, for my intended use:  Address1 is "optional".  But if you leave it off, you'll only match businesses with no address.  See https://github.com/Yelp/yelp-fusion/issues/265

**Comment by gfairchild** [comment]
That's really good to know. It's definitely clear that this is a beta endpoint.
